version: '3.8'
services:
  mysql-master:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/mysql:8.4.5
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"
    volumes:
      - master-data:/var/lib/mysql
      - ./master/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysql-network
    restart: always

  mysql-slave:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/mysql:8.4.5
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: appdb
    ports:
      - "3307:3306"
    volumes:
      - slave-data:/var/lib/mysql
      - ./slave/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysql-network
    depends_on:
      - mysql-master
    restart: always

networks:
  mysql-network:
    driver: bridge

volumes:
  master-data:
  slave-data: