# ubuntu:24.04
FROM registry.cn-hangzhou.aliyuncs.com/macroldj/ubuntu:24.04

# update ubuntu source
RUN sed -i 's/http:\/\/archive.ubuntu.com/http:\/\/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    sed -i 's/http:\/\/security.ubuntu.com/http:\/\/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt-get update && \
    apt -y upgrade && \
    apt -y install --no-install-recommends \
    apt-utils \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    locales \
    net-tools \
    procps \
    sudo \
    vim \
    wget \
    xz-utils \
    zip \
    zlib1g \
    zlib1g-dev \
    && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/*.deb && \
    rm -rf /var/cache/apt/archives/partial/*.deb && \
    rm -rf /var/cache/apt/*.bin

# ubuntu时区
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo 'Asia/Shanghai' > /etc/timezone
