version: '3'
services:
  mongo:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/mongodb-community-server:8.0.3-ubuntu2204
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodb_data: