version: '3.0'
services:
  nginx:
    container_name: nginx
    image: macroldj/nginx:1.21
    build:
      context: ""
      args:
        - NGINX_VER=1.21
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./log:/var/log/nginx:rw
#      - ./index.html:/var/www/index.html:ro
    restart: "always"