FROM 192.168.9.37/devops/python3.11.9-base:v1.0.1

# install utils
ADD wkhtmltox-0.12.6-1.centos7.x86_64.rpm /tmp/wkhtmltox-0.12.6-1.centos7.x86_64.rpm
RUN yum install -y /tmp/wkhtmltox-0.12.6-1.centos7.x86_64.rpm && \
    rm -rf /tmp/wkhtmltox-0.12.6-1.centos7.x86_64.rpm

# set timezone
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

ADD requirements-base.txt /tmp/requirements-base.txt

RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com \
    -r /tmp/requirements-base.txt
