# 使用 Ubuntu 22.04 作为基础镜像
FROM registry.cn-hangzhou.aliyuncs.com/macroldj/ubuntu:22.04-base

# 更新包列表并安装必要的工具和常见调试工具
RUN apt-get install -y --no-install-recommends \
    apt-utils \
    curl \
    cmake \
    build-essential \
    gcc \
    g++-multilib \
    locales \
    make \
    gcovr \
    wget \
    && rm -rf /var/lib/apt/lists/*
