version: '3'

services:
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

volumes:
  redis-data: