version: '3'

services:
  nginx:
    image: nginx:proxy-1.25.0
    restart: always
    ports:
      - '28888:28888'
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    healthcheck:
      test: curl --fail http://localhost:80||exit 1
      interval: 30s
      timeout: 5s
      retries: 6
