FROM registry.cn-hangzhou.aliyuncs.com/macroldj/ubuntu:22.04

# Author: macroldj
# Description: Node.js 18.x

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

