version: '3.8'
services:
  redis-master:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    command: redis-server --requirepass redis123
    networks:
      - redis-network
    restart: always

  redis-slave-1:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    volumes:
      - redis-slave-1-data:/data
    command: redis-server --slaveof redis-master 6379 --masterauth redis123 --requirepass redis123
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: always

  redis-slave-2:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    volumes:
      - redis-slave-2-data:/data
    command: redis-server --slaveof redis-master 6379 --masterauth redis123 --requirepass redis123
    networks:
      - redis-network
    depends_on:
      - redis-master
    restart: always

  sentinel-1:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel-1.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: always

  sentinel-2:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel-2.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: always

  sentinel-3:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel-3.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - redis-network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    restart: always

networks:
  redis-network:
    driver: bridge

volumes:
  redis-master-data:
  redis-slave-1-data:
  redis-slave-2-data:
