version: "3.8"

services:
  redis-cluster-0:
    container_name: redis-cluster-0
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    restart: always
    network_mode: host
    volumes:
      - ./redis/redis-cluster-0/redis.conf:/etc/usr/local/redis.conf
      - redis-cluster-0:/data
    command: "redis-server /etc/usr/local/redis.conf"

  redis-cluster-1:
    container_name: redis-cluster-1
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    network_mode: host
    restart: always
    volumes:
      - ./redis/redis-cluster-1/redis.conf:/etc/usr/local/redis.conf
      - redis-cluster-1:/data
    command: "redis-server /etc/usr/local/redis.conf"

  redis-cluster-2:
    container_name: redis-cluster-2
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    network_mode: host
    restart: always
    volumes:
      - ./redis/redis-cluster-2/redis.conf:/etc/usr/local/redis.conf
      - redis-cluster-2:/data
    command: "redis-server /etc/usr/local/redis.conf"

  redis-cluster-3:
    container_name: redis-cluster-3
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    restart: always
    network_mode: host
    volumes:
      - ./redis/redis-cluster-3/redis.conf:/etc/usr/local/redis.conf
      - redis-cluster-3:/data
    command: "redis-server /etc/usr/local/redis.conf"

  redis-cluster-4:
    container_name: redis-cluster-4
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    restart: always
    network_mode: host
    volumes:
      - ./redis/redis-cluster-4/redis.conf:/etc/usr/local/redis.conf
      - redis-cluster-4:/data
    command: "redis-server /etc/usr/local/redis.conf"

  redis-cluster-5:
    container_name: redis-cluster-5
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    restart: always
    network_mode: host
    volumes:
      - ./redis/redis-cluster-5/redis.conf:/etc/usr/local/redis.conf
      - redis-cluster-5:/data
    command: "redis-server /etc/usr/local/redis.conf"


  redis-cluster-init:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:6.2.18
    container_name: redis-cluster-init
    restart: "no"
    network_mode: host
    depends_on:
      - redis-cluster-0
      - redis-cluster-1
      - redis-cluster-2
      - redis-cluster-3
      - redis-cluster-4
      - redis-cluster-5
    command: >
      /bin/sh -c "
      sleep 10 &&
      redis-cli --cluster create 127.0.0.1:26379 127.0.0.1:26380 127.0.0.1:26381 127.0.0.1:26382 127.0.0.1:26383 127.0.0.1:26384 --cluster-replicas 1 --cluster-yes
      "

volumes:
  redis-cluster-0:
  redis-cluster-1:
  redis-cluster-2:
  redis-cluster-3:
  redis-cluster-4:
  redis-cluster-5:

