FROM 100.64.10.37/security/jj-code-web:v2.0.1

COPY ./cd.tkoffice.cn.cer /etc/nginx/cert/cd.tkoffice.cn.cer
COPY ./cd.tkoffice.cn.key /etc/nginx/cert/cd.tkoffice.cn.key
COPY ./nginx.conf /etc/nginx/nginx.conf