FROM registry.cn-hangzhou.aliyuncs.com/macroldj/ubuntu:22.04-base


# install go
COPY go1.22.12.linux-amd64.tar.gz /usr/local/

RUN tar -C /usr/local -xzf /usr/local/go1.22.12.linux-amd64.tar.gz && \
    rm -rf /usr/local/go1.22.12.linux-amd64.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/bin/gofmt

# goproxy setings
RUN go env -w GO111MODULE=on && go env -w GOPROXY=https://goproxy.cn,directdate

# install go debug tools
RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install github.com/ramya-rao-a/go-outline@latest && \
    go install github.com/acroca/go-symbols@latest && \
    go install github.com/joefitzgerald/go-vet-cov@latest && \
    go install github.com/kyoh86/richgo@latest && \
    go install github.com/golang/lint/golint@latest && \
    go install golang.org/x/tools/cmd/godoc@latest && \
    go install golang.org/x/tools/cmd/gorename@latest && \
    go install golang.org/x/tools/cmd/goimports@latest && \
    go install golang.org/x/tools/cmd/gopls@latest