FROM registry.cn-hangzhou.aliyuncs.com/macroldj/ubuntu:22.04-base

LABEL maintainer="Durgin.Li <dejinx@qq.com>"
LABEL description="PulseDuty"
LABEL version="1.0"

WORKDIR /app

ENV env=release

# 只复制构建产物
COPY --from=builder /app/bin/pulse-duty /app/bin/pulse-duty

# 使用非 root 用户运行
RUN useradd -r -u 1000 -g root pduty
USER pduty

EXPOSE 8001

CMD ["./bin/server"]