---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 4
  clusterVersion: v7
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
  persistenceEnabled: true
  kubernetesConfig:
    imagePullSecrets:
      - name: macroldj
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:v7.0.15
    imagePullPolicy: Always
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: juicefs-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
