---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name:  redis-replication
spec:
  clusterSize: 3
  kubernetesConfig:
    imagePullSecrets:
      - name: macroldj
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/redis:v7.0.15
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: juicefs-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
