version: "3"
services:
  es:
    image: 100.64.10.37/devops/elasticsearch:7.14.0
    container_name: es
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx2g"
      - discovery.type=single-node
      - TAKE_FILE_OWNERSHIP=true
    ports:
      - "9200:9200"
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
      - ./logs/es:/usr/share/elasticsearch/logs
    privileged: true

  mysql:
    container_name: mysql-server
    ports:
      - "3306:3306"
    image: 100.64.10.37/devops/mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/lib/mysql-logs:rw
    environment:
      MYSQL_ROOT_PASSWORD: "root@0808"
    restart: always

  redis:
    image: 100.64.10.37/devops/redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/redis/data:rw
      - ./logs/redis:/var/log/:rw
    restart: always

  nacos:
    image: 100.64.10.37/devops/nacos-server:2.0.1
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
    environment:
      - MODE=standalone
    volumes:
      - ./data/nacos:/home/nacos/data
      - ./log/nacos:/home/nacos/logs

  zookeeper:
    image: 100.64.10.37/devops/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "./data/zookeeper:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 100.64.10.37/devops/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "./data/kafka:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper