version: '3'

services:
  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - '9000:9000'
      - '13306:13306'
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    healthcheck:
      test: curl --fail http://localhost:80||exit 1
      interval: 30s
      timeout: 5s
      retries: 6
