version: '3'

services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/nginx:1.21.1
    restart: always
    ports:
      - '80:80'
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./html:/usr/share/nginx/html"
    healthcheck:
      test: curl --fail http://localhost:80||exit 1
      interval: 30s
      timeout: 5s
      retries: 6
