version: '3.8'

services:
  clickhouse:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/clickhouse-server:25.4
    container_name: clickhouse-server
    ports:
      - "8123:8123"   # HTTP 接口
      - "9000:9000"   # 原生客户端接口
      - "9009:9009"   # 复制端口
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      - ./config:/etc/clickhouse-server/config.d
      - ./users:/etc/clickhouse-server/users.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DB=default
    restart: always

volumes:
  clickhouse-data:
  clickhouse-logs: