version: '3'

services:
  redis:
    image: redis:4.0.2
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 30s
      retries: 6
      start_period: 5s

  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: rabbitmqctl ping
      interval: 10s
      timeout: 30s
      retries: 6
      start_period: 10s

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    environment:
      - DJANGO=django
    depends_on:
      - django
    healthcheck:
      test: curl --fail http://localhost:80||exit 1
      interval: 10s
      timeout: 5s
      retries: 6

  django:
    build:
      context: .
    image: macroldj/devops:v1.0.1
    restart: "always"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 300m
    environment:
      - REDIS_IP=redis
      - RABBITMQ_IP=rabbitmq
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - SENTRY_IP=192.168.1.5
    working_dir: /home/workspace
    volumes:
      - ./media/temp:/home/workspace/media/temp
      - ./db.sqlite3:/home/workspace/db.sqlite3
    command: ["python","manage.py","runserver","0.0.0.0:8000"]
    depends_on:
      - rabbitmq
      - redis
    links:
      - redis
      - rabbitmq
    healthcheck:
      test: curl --fail http://localhost:8000||exit 1
      interval: 10s
      timeout: 5s
      retries: 6

  celery:
    image: macroldj/devops:v1.0.1
    restart: "always"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 300m
    environment:
      - RABBITMQ_IP=rabbitmq
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - REDIS_IP=redis
      - SENTRY_IP=192.168.1.5
    working_dir: /home/workspace
    command: ["celery","-A","devops","worker","-l","info"]
    depends_on:
      - rabbitmq
      - redis
      - django
    links:
      - redis
      - rabbitmq
      - django
    healthcheck:
      test: celery inspect ping -b amqp://admin:admin@rabbitmq:5672 -d celery@$$HOSTNAME || exit 1
      interval: 20s
      timeout: 5s
      retries: 6
      start_period: 20s

  flower:
    image: macroldj/flower:v1
    working_dir: /home/workspace
    ports:
      - "5555:5555"
    environment:
      - RABBITMQ_IP=rabbitmq
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - C_FORCE_ROOT=true
    depends_on:
      - rabbitmq
      - celery
      - django
    restart: "always"
    links:
      - rabbitmq
      - celery
    healthcheck:
      test: celery inspect ping -b amqp://admin:admin@rabbitmq:5672 || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
