version: "3"
services:
  jj-oms-code-web:
    network_mode: host
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "9527:80"
    healthcheck:
      test: curl http://localhost:80||exit 1
      interval: 30s
      timeout: 5s
      retries: 6

