version: '3.7'

services:
  minio:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/minio:RELEASE.2025-04-22T22-12-26Z
    hostname: minio
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9002:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

volumes:
  minio-data: