version: '3'

services:
  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - '443:443'
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - './cert:/etc/nginx/cert'
      - './logs/nginx/:/var/log/nginx/'
    healthcheck:
      test: curl --fail http://localhost:80||exit 1
      interval: 30s
      timeout: 5s
      retries: 6